### PR TITLE
Migrate to ZIO 2.0.0-RC1

### LINKED ISSUE #197: Upgrade to ZIO 2.0
ZIO 2.0 is at Milestone 4, with an RC expected in the next few weeks.
https://github.com/zio/zio/releases/tag/v2.0.0-M4

The API is nearly stable at this point, so any early migration work against this version should pay off towards the official 2.0 release.

The progress is being tracked here:
zio/zio#5470

The Stream Encoding work in progress is the only area where the API might still change before the RC.

We are actively working on a ScalaFix rule that will cover the bulk of the simple API changes:
https://github.com/zio/zio/blob/series/2.x/scalafix/rules/src/main/scala/fix/Zio2Upgrade.scala
We highly recommend starting with that, and then working through any remaining compilation errors :)

To assist with the rest of the migration, we have created this guide:
https://zio.dev/howto/migrate/zio-2.x-migration-guide/

If you would like assistance with the migration from myself or other ZIO contributors, please let us know!

### PR DESCRIPTION
**Pull request by zagyi**
Waiting for `zio-nio` to be migrated, but otherwise should be good to go.
Fixes #197

### CODE REVIEW

**Comment by regis-leray** [comment]
thank you im going to create a branch 2.0 to publish this artifact

**Comment by swoogles** [comment]
@zagyi ZioNio has been released for 2.0.0-RC1, so that blocker is gone :)

**Comment by swoogles** [comment]
@zagyi ZioNio has been released for 2.0.0-RC1, so that blocker is gone :)

**Comment by Fristi** [comment]
ZIO 2 is almost coming, do you need help to get this to this to the finish line?

**Comment by regis-leray** [comment]
@Fristi it would be good to migrate to github actions
https://github.com/zio/zio-ftp/issues/235

If you have time, and we can update right after to ZIO 2.0

Currently PR are blocked since build are stuck.

```

#!/bin/bash -eo pipefail
while $(ps aux | grep -i ' apt ' | grep -v grep > /dev/null); do sleep 1; done # Wait for apt to be ready
sudo add-apt-repository ppa:openjdk-r/ppa -y
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 78BD65473CB3BD13
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 5DC22404A6F9F1CA

sudo apt update
sudo apt install openjdk-${JDK_VERSION}-jdk -y

gpg: keyring `/tmp/tmp02tje16i/secring.gpg' created
gpg: keyring `/tmp/tmp02tje16i/pubring.gpg' created
gpg: requesting key 86F44E2A from hkp server keyserver.ubuntu.com
gpg: /tmp/tmp02tje16i/trustdb.gpg: trustdb created
gpg: key 86F44E2A: public key "Launchpad OpenJDK builds (all archs)" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK
Executing: /tmp/tmp.kUxz2Z2T1M/gpg.1.sh --keyserver
keyserver.ubuntu.com
--recv-keys
78BD65473CB3BD13
gpg: requesting key 3CB3BD13 from hkp server keyserver.ubuntu.com
gpg: key D38B4796: "Google Inc. (Linux Packages Signing Authority) <linux-packages-keymaster@google.com>" 19 new signatures
gpg: key D38B4796: "Google Inc. (Linux Packages Signing Authority) <linux-packages-keymaster@google.com>" 3 new subkeys
gpg: Total number processed: 1
gpg:            new subkeys: 3
gpg:         new signatures: 19
Executing: /tmp/tmp.C7RP4v9WMt/gpg.1.sh --keyserver
keyserver.ubuntu.com
--recv-keys
5DC22404A6F9F1CA
gpg: requesting key A6F9F1CA from hkp server keyserver.ubuntu.com
gpg: key A6F9F1CA: public key "Heroku Inc. <support@heroku.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
0% [Working]Hit:1 http://us-east-1.ec2.archive.ubuntu.com/ubuntu xenial InRelease
0% [Connecting to security.ubuntu.com (91.189.91.39)] [Connecting to ppa.launchGet:2 http://us-east-1.ec2.archive.ubuntu.com/ubuntu xenial-updates InRelease [99.8 kB]
Get:3 http://us-east-1.ec2.archive.ubuntu.com/ubuntu xenial-backports InRelease [97.4 kB]
0% [Waiting for headers] [Connecting to ppa.launchpad.net (91.189.95.85)] [WaitGet:4 http://dl.google.com/linux/chrome/deb stable InRelease [1,811 B]         
0% [Waiting for headers] [Connecting to ppa.launchpad.net (91.189.95.85)]      Get:5 http://security.ubuntu.com/ubuntu xenial-security InRelease [99.8 kB]
0% [5 InRelease 14.2 kB/99.8 kB 14%] [Connecting to ppa.launchpad.net (91.189.90% [1 InRelease gpgv 247 kB] [5 InRelease 14.2 kB/99.8 kB 14%] [Connecting to p0% [1 InRelease gpgv 247 kB] [Connecting to ppa.launchpad.net (91.189.95.85)]  Get:6 https://download.docker.com/linux/ubuntu xenial InRelease [66.2 kB]    
0% [1 InRelease gpgv 247 kB] [6 InRelease 32.3 kB/66.2 kB 49%] [Waiting for hea0% [1 InRelease gpgv 247 kB] [Waiting for headers]                             Get:7 https://cli-assets.heroku.com/apt ./ InRelease [2,895 B]
0% [1 InRelease gpgv 247 kB] [Waiting for headers] [7 InRelease 2,895 B/2,895 B0% [1 InRelease gpgv 247 kB] [Waiting for headers]                             0% [Waiting for headers]                          0% [2 InRelease gpgv 99.8 kB] [Waiting for headers]Get:8 http://ppa.launchpad.net/git-core/ppa/ubuntu xenial InRelease [20.8 kB]
0% [2 InRelease gpgv 99.8 kB] [8 InRelease 2,572 B/20.8 kB 12%]0% [8 InRelease 11.3 kB/20.8 kB 54%]                           0% [3 InRelease gpgv 97.4 kB] [Waiting for headers] [8 InRelease 11.3 kB/20.8 kGet:9 http://us-east-1.ec2.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [2,049 kB]
0% [3 InRelease gpgv 97.4 kB] [9 Packages 26.6 kB/2,049 kB 1%] [8 InRelease 11.0% [3 InRelease gpgv 97.4 kB] [8 InRelease 14.2 kB/20.8 kB 68%]                0% [9 Packages store 0 B] [3 InRelease gpgv 97.4 kB] [Waiting for headers] [8 IGet:10 http://us-east-1.ec2.archive.ubuntu.com/ubuntu xenial-updates/main Translation-en [461 kB]
0% [9 Packages store 0 B] [3 InRelease gpgv 97.4 kB] [10 Translation-en 25.9 kB0% [9 Packages store 0 B] [10 Translation-en 461 kB/461 kB 100%] [8 InRelease 2Get:11 http://us-east-1.ec2.archive.ubuntu.com/ubuntu xenial-updates/restricted amd64 Packages [10.2 kB]
Get:12 http://us-east-1.ec2.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [1,219 kB]
0% [9 Packages store 0 B] [12 Packages 98.6 kB/1,219 kB 8%] [Connecting to ppa.0% [9 Packages store 0 B] [4 InRelease gpgv 1,811 B] [12 Packages 98.6 kB/1,2190% [9 Packages store 0 B] [4 InRelease gpgv 1,811 B] [Connecting to ppa.launchpGet:13 http://us-east-1.ec2.archive.ubuntu.com/ubuntu xenial-updates/universe Translation-en [358 kB]
0% [9 Packages store 0 B] [4 InRelease gpgv 1,811 B] [13 Translation-en 25.9 kB0% [9 Packages store 0 B] [4 InRelease gpgv 1,811 B] [Connecting to ppa.launchpGet:14 http://us-east-1.ec2.archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages [22.6 kB]
0% [9 Packages store 0 B] [4 InRelease gpgv 1,811 B] [14 Packages 0 B/22.6 kB 00% [9 Packages store 0 B] [4 InRelease gpgv 1,811 B] [Connecting to ppa.launchp0% [9 Packages store 0 B] [Waiting for headers] [Connecting to ppa.launchpad.neGet:15 http://us-east-1.ec2.archive.ubuntu.com/ubuntu xenial-updates/multiverse Translation-en [8,476 B]
0% [9 Packages store 0 B] [Waiting for headers] [Connecting to ppa.launchpad.ne0% [9 Packages store 0 B] [5 InRelease gpgv 99.8 kB] [Waiting for headers] [ConGet:16 http://us-east-1.ec2.archive.ubuntu.com/ubuntu xenial-backports/main amd64 Packages [9,812 B]
0% [9 Packages store 0 B] [5 InRelease gpgv 99.8 kB] [16 Packages 0 B/9,812 B 00% [9 Packages store 0 B] [5 InRelease gpgv 99.8 kB] [Connecting to ppa.launchpGet:17 http://us-east-1.ec2.archive.ubuntu.com/ubuntu xenial-backports/universe amd64 Packages [11.3 kB]
0% [9 Packages store 0 B] [5 InRelease gpgv 99.8 kB] [17 Packages 11.3 kB/11.3 0% [9 Packages store 0 B] [5 InRelease gpgv 99.8 kB] [Waiting for headers] [ConGet:18 http://us-east-1.ec2.archive.ubuntu.com/ubuntu xenial-backports/universe Translation-en [4,476 B]
0% [9 Packages store 0 B] [5 InRelease gpgv 99.8 kB] [18 Translation-en 4,476 B0% [9 Packages store 0 B] [5 InRelease gpgv 99.8 kB] [Connecting to ppa.launchpGet:19 http://dl.google.com/linux/chrome/deb stable/main amd64 Packages [1,090 B]
0% [9 Packages store 0 B] [5 InRelease gpgv 99.8 kB] [Waiting for headers] [19 0% [9 Packages store 0 B] [5 InRelease gpgv 99.8 kB] [Waiting for headers]     0% [9 Packages store 0 B] [Waiting for headers]                           0% [9 Packages store 0 B] [6 InRelease gpgv 66.2 kB] [Waiting for headers]Get:20 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [1,648 kB]
0% [9 Packages store 0 B] [6 InRelease gpgv 66.2 kB] [20 Packages 8,477 B/1,648Get:21 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu xenial InRelease [20.8 kB]
0% [9 Packages store 0 B] [6 InRelease gpgv 66.2 kB] [20 Packages 162 kB/1,648 0% [9 Packages store 0 B] [20 Packages 650 kB/1,648 kB 39%] [21 InRelease 11.3 0% [9 Packages store 0 B] [7 InRelease gpgv 2,895 B] [20 Packages 686 kB/1,648 Get:22 https://download.docker.com/linux/ubuntu xenial/stable amd64 Packages [21.0 kB]
0% [9 Packages store 0 B] [7 InRelease gpgv 2,895 B] [20 Packages 751 kB/1,648 0% [9 Packages store 0 B] [7 InRelease gpgv 2,895 B] [20 Packages 751 kB/1,648 0% [9 Packages store 0 B] [7 InRelease gpgv 2,895 B] [21 InRelease 14.2 kB/20.8Err:7 https://cli-assets.heroku.com/apt ./ InRelease                           
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6DB5542C356545CF
0% [9 Packages store 0 B] [Waiting for headers] [21 InRelease 14.2 kB/20.8 kB 60% [9 Packages store 0 B] [8 InRelease gpgv 20.8 kB] [Waiting for headers] [21 Get:23 http://security.ubuntu.com/ubuntu xenial-security/main Translation-en [360 kB]
0% [9 Packages store 0 B] [8 InRelease gpgv 20.8 kB] [23 Translation-en 21.2 kBIgn:24 https://packagecloud.io/circleci/trusty/ubuntu xenial InRelease         
0% [9 Packages store 0 B] [8 InRelease gpgv 20.8 kB] [23 Translation-en 218 kB/0% [9 Packages store 0 B] [8 InRelease gpgv 20.8 kB] [21 InRelease 14.2 kB/20.80% [9 Packages store 0 B] [8 InRelease gpgv 20.8 kB] [Waiting for headers]     Get:25 http://security.ubuntu.com/ubuntu xenial-security/restricted amd64 Packages [9,824 B]
0% [9 Packages store 0 B] [8 InRelease gpgv 20.8 kB] [25 Packages 9,824 B/9,8240% [9 Packages store 0 B] [8 InRelease gpgv 20.8 kB] [Waiting for headers]     Get:26 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [785 kB]
0% [9 Packages store 0 B] [8 InRelease gpgv 20.8 kB] [26 Packages 175 kB/785 kB0% [9 Packages store 0 B] [8 InRelease gpgv 20.8 kB]                           Get:27 http://security.ubuntu.com/ubuntu xenial-security/universe Translation-en [225 kB]
0% [9 Packages store 0 B] [8 InRelease gpgv 20.8 kB] [27 Translation-en 110 kB/0% [9 Packages store 0 B] [8 InRelease gpgv 20.8 kB]                           0% [9 Packages store 0 B] [Waiting for headers]     0% [9 Packages store 0 B] [21 InRelease gpgv 20.8 kB] [Waiting for headers] [CoGet:28 http://security.ubuntu.com/ubuntu xenial-security/multiverse amd64 Packages [7,864 B]
0% [9 Packages store 0 B] [21 InRelease gpgv 20.8 kB] [28 Packages 7,864 B/7,860% [9 Packages store 0 B] [21 InRelease gpgv 20.8 kB] [Waiting for headers] [CoErr:29 https://packagecloud.io/circleci/trusty/ubuntu xenial Release           
  404  Not Found
0% [9 Packages store 0 B] [21 InRelease gpgv 20.8 kB] [Waiting for headers] [CoGet:30 http://security.ubuntu.com/ubuntu xenial-security/multiverse Translation-en [2,672 B]
0% [9 Packages store 0 B] [21 InRelease gpgv 20.8 kB] [30 Translation-en 2,672 0% [9 Packages store 0 B] [21 InRelease gpgv 20.8 kB] [Connecting to ppa.launch0% [9 Packages store 0 B] [Connecting to ppa.launchpad.net (91.189.95.85)]     0% [Waiting for headers]                                                  0% [10 Translation-en store 0 B] [Waiting for headers]Get:31 http://ppa.launchpad.net/git-core/ppa/ubuntu xenial/main amd64 Packages [3,328 B]
0% [10 Translation-en store 0 B] [31 Packages 2,672 B/3,328 B 80%]0% [10 Translation-en store 0 B]                                  0% [Connecting to ppa.launchpad.net (91.189.95.85)]0% [11 Packages store 0 B] [Connecting to ppa.launchpad.net (91.189.95.85)]0% [Connecting to ppa.launchpad.net (91.189.95.85)]                        0% [12 Packages store 0 B] [Connecting to ppa.launchpad.net (91.189.95.85)]Get:32 http://ppa.launchpad.net/git-core/ppa/ubuntu xenial/main Translation-en [2,432 B]
0% [12 Packages store 0 B] [32 Translation-en 2,432 B/2,432 B 100%]        0% [12 Packages store 0 B] [Connecting to ppa.launchpad.net (91.189.95.85)]0% [Connecting to ppa.launchpad.net (91.189.95.85)]                        0% [13 Translation-en store 0 B] [Connecting to ppa.launchpad.net (91.189.95.850% [Waiting for headers]                                                       0% [14 Packages store 0 B] [Waiting for headers]0% [Waiting for headers]                        0% [15 Translation-en store 0 B] [Waiting for headers]0% [Waiting for headers]                              0% [16 Packages store 0 B] [Waiting for headers]0% [Waiting for headers]                        0% [17 Packages store 0 B] [Waiting for headers]0% [Waiting for headers]                        0% [18 Translation-en store 0 B] [Waiting for headers]0% [Waiting for headers]                              0% [19 Packages store 0 B] [Waiting for headers]0% [Waiting for headers]                        0% [22 Packages store 0 B] [Waiting for headers]0% [Waiting for headers]                        0% [20 Packages store 0 B] [Waiting for headers]Get:33 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu xenial/main amd64 Packages [16.6 kB]
0% [20 Packages store 0 B] [33 Packages 2,670 B/16.6 kB 16%]0% [20 Packages store 0 B] [Connecting to ppa.launchpad.net (91.189.95.85)]0% [Waiting for headers]                                                   0% [23 Translation-en store 0 B] [Waiting for headers]Get:34 http://ppa.launchpad.net/openjdk-r/ppa/ubuntu xenial/main Translation-en [2,612 B]
0% [23 Translation-en store 0 B] [34 Translation-en 2,612 B/2,612 B 100%]0% [23 Translation-en store 0 B]                                         0% [Working]                    0% [25 Packages store 0 B]0% [Working]              0% [26 Packages store 0 B]0% [Working]              0% [27 Translation-en store 0 B]0% [Working]                    0% [28 Packages store 0 B]0% [Working]              0% [30 Translation-en store 0 B]0% [Working]                    0% [31 Packages store 0 B]0% [Working]              0% [32 Translation-en store 0 B]0% [Working]                    0% [33 Packages store 0 B]0% [Working]              0% [34 Translation-en store 0 B]0% [Working]                    Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://cli-assets.heroku.com/apt ./ InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6DB5542C356545CF
E: The repository 'https://packagecloud.io/circleci/trusty/ubuntu xenial Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Exited with code exit status 100
CircleCI received exit code 100
```

**Comment by regis-leray** [comment]
https://github.com/zio/zio-ftp/pull/246

**Pull request closed without merging**
