### PR TITLE
UnsecureFtp - expose failure in error channel for readFile()

### PR DESCRIPTION
**Pull request by regis-leray**
@codingismy11to7 it should resolve the issue :) Tell me what you think.

You can now recover the exception from the specific Error `FileTransferIncompleteError` with `.catchSome()`.

Thanks again for your review, i wrote the code a little bit too fast with my kids around...

I need to provide unit test but dont have yet a strategy to fail the download (maybe use mock 😢 )

### CODE REVIEW

**Comment by codingismy11to7** [comment]
yeah that seems like it'd work better... let me check out this branch and try it out and write some unit tests. I'm starting on it now, I'll send a PR based on this or a patch or something in an hour or two

**Comment by regis-leray** [comment]
@codingismy11to7 thank you again for your contribution.

**Comment by codingismy11to7** [comment]
so, looks like my unit test is showing that the failure is still being propagated as a defect. I'm going to try `ZStream.ensuring` and see if that works.

**Comment by codingismy11to7** [comment]
I fixed it with `zipLeft`, PR incoming shortly

**Comment by codingismy11to7** [comment]
opened https://github.com/zio/zio-ftp/pull/216 that puts another commit onto this branch, didn't know if i should open a PR that puts both commits onto master, I can change to doing that if you prefer

**Pull request closed without merging**
