### PR TITLE
Sftp.upload allow to set open modes

### PR DESCRIPTION
**Pull request by Fristi**

### CODE REVIEW

**Comment by regis-leray** [comment]
Could you please open a github issue, with more informations about the problem (full stack trace) and the current use case you are handling in your program.

Thank you

Are you creating a new file, or overwriting ?

**Comment by Fristi** [comment]
@regis-leray Posted error at #253

**Comment by regis-leray** [comment]
might be related to https://github.com/zio/zio-ftp/pull/252/files

we dont validate operation is completed after the store the file

**Comment by Fristi** [comment]
Would you like this feature @regis-leray ?

**Pull request closed without merging**
