### PR TITLE
Zio 2 upgrade

### PR DESCRIPTION
**Pull request by regis-leray**

### CODE REVIEW

**Comment by Fristi** [comment]
Ah also started on this :) You seem to have already most stuff work except JVM 17 and Scala 2.11, let me know if I can help

**Comment by regis-leray** [comment]
@zagyi thank you for your work

@Fristi thank you everything is handle.

**Comment by Fristi** [comment]
I'll have a look

**Comment by Fristi** [comment]
Docs fixed in #247 , would be cool if you can do a release with 2.0.0-RC6 @regis-leray

**Comment by Fristi** [comment]
Great! Thank you :) Let the migration begin

**Pull request merged**
